<h3 id="writing-package-vignettes" class="section">1.4 Writing package vignettes</h3>
<p><a href="" id="index-vignettes"></a> <a href="" id="index-Sweave"></a></p>
<p>In addition to the help files in Rd format, R packages allow the inclusion of documents in arbitrary other formats. The standard location for these is subdirectory inst/doc of a source package, the contents will be copied to subdirectory doc when the package is installed. Pointers from package help indices to the installed documents are automatically created. Documents in inst/doc can be in arbitrary format, however we strongly recommend providing them in PDF format, so users on almost all platforms can easily read them. To ensure that they can be accessed from a browser (as an HTML index is provided), the file names should start with an ASCII letter and be comprised entirely of ASCII letters or digits or hyphen or underscore.</p>
<p>A special case is <em>package vignettes</em>. Vignettes are documents in PDF or HTML format obtained from plain text literate source files from which R knows how to extract R code and create output (in PDF/HTML or intermediate LaTeX). Vignette engines do this work, using “tangle” and “weave” functions respectively. Sweave, provided by the R distribution, is the default engine. Since R version 3.0.0, other vignette engines besides Sweave are supported; see <a href="#Non_002dSweave-vignettes">Non-Sweave vignettes</a>.</p>
<p>Package vignettes have their sources in subdirectory vignettes of the package sources. Note that the location of the vignette sources only affects <code class="calibre2">R CMD build</code> and <code class="calibre2">R CMD check</code>: the tarball built by <code class="calibre2">R CMD build</code> includes in inst/doc the components intended to be installed.</p>
<p>Sweave vignette sources are normally given the file extension .Rnw or .Rtex, but for historical reasons extensions<a href="concept-index.html#FOOT54" id="DOCF54"><sup>54</sup></a> .Snw and .Stex are also recognized. Sweave allows the integration of LaTeX documents: see the <code class="calibre2">Sweave</code> help page in R and the <code class="calibre2">Sweave</code> vignette in package <strong>utils</strong> for details on the source document format.</p>
<p>Package vignettes are tested by <code class="calibre2">R CMD check</code> by executing all R code chunks they contain (except those marked for non-evaluation, e.g., with option <code class="calibre2">eval=FALSE</code> for Sweave). The R working directory for all vignette tests in <code class="calibre2">R CMD check</code> is a <em>copy</em> of the vignette source directory. Make sure all files needed to run the R code in the vignette (data sets, …) are accessible by either placing them in the inst/doc hierarchy of the source package or by using calls to <code class="calibre2">system.file()</code>. All other files needed to re-make the vignettes (such as LaTeX style files, BibTeX input files and files for any figures not created by running the code in the vignette) must be in the vignette source directory. <code class="calibre2">R CMD check</code> will check that vignette production has succeeded by comparing modification times of output files in inst/doc with the source in vignettes.</p>
<p><code class="calibre2">R CMD build</code> will automatically<a href="concept-index.html#FOOT55" id="DOCF55"><sup>55</sup></a> create the (PDF or HTML versions of the) vignettes in inst/doc for distribution with the package sources. By including the vignette outputs in the package sources it is not necessary that these can be re-built at install time, i.e., the package author can use private R packages, screen snapshots and LaTeX extensions which are only available on his machine.<a href="concept-index.html#FOOT56" id="DOCF56"><sup>56</sup></a></p>
<p>By default <code class="calibre2">R CMD build</code> will run <code class="calibre2">Sweave</code> on all Sweave vignette source files in vignettes. If Makefile is found in the vignette source directory, then <code class="calibre2">R CMD build</code> will try to run <code class="calibre2">make</code> after the <code class="calibre2">Sweave</code> runs, otherwise <code class="calibre2">texi2pdf</code> is run on each .tex file produced.</p>
<p>The first target in the Makefile should take care of both creation of PDF/HTML files and cleaning up afterwards (including after <code class="calibre2">Sweave</code>), i.e., delete all files that shall not appear in the final package archive. Note that if the <code class="calibre2">make</code> step runs R it needs to be careful to respect the environment values of <code class="calibre2">R_LIBS</code> and <code class="calibre2">R_HOME</code><a href="concept-index.html#FOOT57" id="DOCF57"><sup>57</sup></a>. Finally, if there is a Makefile and it has a ‘clean:’ target, <code class="calibre2">make clean</code> is run.</p>
<p>All the usual <em>caveats</em> about including a Makefile apply. It must be portable (no GNU extensions), use LF line endings and must work correctly with a parallel <code class="calibre2">make</code>: too many authors have written things like</p>
<div class="example">
<pre class="example1"><code>## BAD EXAMPLE
all: pdf clean

pdf: ABC-intro.pdf ABC-details.pdf

%.pdf:  %.tex
        texi2dvi --pdf &#36;*

clean:
        rm *.tex ABC-details-*.pdf</code></pre>
</div>
<p>which will start removing the source files whilst <code class="calibre2">pdflatex</code> is working.</p>
<p>Metadata lines can be placed in the source file, preferably in LaTeX comments in the preamble. One such is a <code class="calibre2">&#92;VignetteIndexEntry</code> of the form</p>
<div class="example">
<pre class="example1"><code>%&#92;VignetteIndexEntry{Using Animal}</code></pre>
</div>
<p>Others you may see are <code class="calibre2">&#92;VignettePackage</code> (currently ignored), <code class="calibre2">&#92;VignetteDepends</code> and <code class="calibre2">&#92;VignetteKeyword</code> (which replaced <code class="calibre2">&#92;VignetteKeywords</code>). These are processed at package installation time to create the saved data frame Meta/vignette.rds, but only the <code class="calibre2">&#92;VignetteIndexEntry</code> and <code class="calibre2">&#92;VignetteKeyword</code> statements are currently used. The <code class="calibre2">&#92;VignetteEngine</code> statement is described in <a href="#Non_002dSweave-vignettes">Non-Sweave vignettes</a>.</p>
<p>At install time an HTML index for all vignettes in the package is automatically created from the <code class="calibre2">&#92;VignetteIndexEntry</code> statements unless a file index.html exists in directory inst/doc. This index is linked from the HTML help index for the package. If you do supply a inst/doc/index.html file it should contain relative links only to files under the installed doc directory, or perhaps (not really an index) to HTML help files or to the DESCRIPTION file, and be valid HTML as confirmed via the <a href="https://validator.w3.org">W3C Markup Validation Service</a> or <a href="https://validator.nu/">Validator.nu</a>.</p>
<p>Sweave/Stangle allows the document to specify the <code class="calibre2">split=TRUE</code> option to create a single R file for each code chunk: this will not work for vignettes where it is assumed that each vignette source generates a single file with the vignette extension replaced by .R.</p>
<p>Do watch that PDFs are not too large – one in a CRAN package was 72MB! This is usually caused by the inclusion of overly detailed figures, which will not render well in PDF viewers. Sometimes it is much better to generate fairly high resolution bitmap (PNG, JPEG) figures and include those in the PDF document.</p>
<p><a href="" id="index-_002einstall_005fextras-file"></a></p>
<p>When <code class="calibre2">R CMD build</code> builds the vignettes, it copies these and the vignette sources from directory vignettes to inst/doc. To install any other files from the vignettes directory, include a file vignettes/.install_extras which specifies these as Perl-like regular expressions on one or more lines. (See the description of the .Rinstignore file for full details.)</p>
<hr />
<p><a href="" id="Encodings-and-vignettes"></a> <a href="" id="Encodings-and-vignettes-1"></a></p>
<h4 id="encodings-and-vignettes" class="subsection">1.4.1 Encodings and vignettes</h4>
<p>Vignettes will in general include descriptive text, R input, R output and figures, LaTeX include files and bibliographic references. As any of these may contain non-ASCII characters, the handling of encodings can become very complicated.</p>
<p>The vignette source file should be written in ASCII or contain a declaration of the encoding (see below). This applies even to comments within the source file, since vignette engines process comments to look for options and metadata lines. When an engine’s weave and tangle functions are called on the vignette source, it will be converted to the encoding of the current R session.</p>
<p><code class="calibre2">Stangle()</code> will produce an R code file in the current locale’s encoding: for a non-ASCII vignette what that is is recorded in a comment at the top of the file.</p>
<p><code class="calibre2">Sweave()</code> will produce a .tex file in the current encoding, or in UTF-8 if that is declared. Non-ASCII encodings need to be declared to LaTeX via a line like</p>
<div class="example">
<pre class="example1"><code>&#92;usepackage[utf8]{inputenc}</code></pre>
</div>
<p>(It is also possible to use the more recent ‘inputenx’ LaTeX package.) For files where this line is not needed (e.g. chapters included within the body of a larger document, or non-Sweave vignettes), the encoding may be declared using a comment like</p>
<div class="example">
<pre class="example1"><code>%&#92;VignetteEncoding{UTF-8}</code></pre>
</div>
<p>If the encoding is UTF-8, this can also be declared using the declaration</p>
<div class="example">
<pre class="example1"><code>%&#92;SweaveUTF8</code></pre>
</div>
<p>If no declaration is given in the vignette, it will be assumed to be in the encoding declared for the package. If there is no encoding declared in either place, then it is an error to use non-ASCII characters in the vignette.</p>
<p>In any case, be aware that LaTeX may require the ‘usepackage’ declaration.</p>
<p><code class="calibre2">Sweave()</code> will also parse and evaluate the R code in each chunk. The R output will also be in the current locale (or UTF-8 if so declared), and should be covered by the ‘inputenc’ declaration. One thing people often forget is that the R output may not be ASCII even for ASCII R sources, for many possible reasons. One common one is the use of ‘fancy’ quotes: see the R help on <code class="calibre2">sQuote</code>: note carefully that it is not portable to declare UTF-8 or CP1252 to cover such quotes, as their encoding will depend on the locale used to run <code class="calibre2">Sweave()</code>: this can be circumvented by setting <code class="calibre2">options(useFancyQuotes=&quot;UTF-8&quot;)</code> in the vignette.</p>
<p>The final issue is the encoding of figures – this applies only to PDF figures and not PNG etc. The PDF figures will contain declarations for their encoding, but the Sweave option <code class="calibre2">pdf.encoding</code> may need to be set appropriately: see the help for the <code class="calibre2">pdf()</code> graphics device.</p>
<p>As a real example of the complexities, consider the <a href="https://CRAN.R-project.org/package=fortunes"><strong>fortunes</strong></a> package version ‘1.4-0’. That package did not have a declared encoding, and its vignette was in ASCII. However, the data it displays are read from a UTF-8 CSV file and will be assumed to be in the current encoding, so fortunes.tex will be in UTF-8 in any locale. Had <code class="calibre2">read.table</code> been told the data were UTF-8, fortunes.tex would have been in the locale’s encoding.</p>
<hr />
<p><a href="" id="Non_002dSweave-vignettes"></a> <a href="" id="Non_002dSweave-vignettes-1"></a></p>
<h4 id="non-sweave-vignettes" class="subsection">1.4.2 Non-Sweave vignettes</h4>
<p>Vignettes in formats other than Sweave are supported <em>via</em> “vignette engines”. For example <a href="https://CRAN.R-project.org/package=knitr"><strong>knitr</strong></a> version 1.1 or later can create .tex files from a variation on Sweave format, and .html files from a variation on “markdown” format. These engines replace the <code class="calibre2">Sweave()</code> function with other functions to convert vignette source files into LaTeX files for processing into .pdf, or directly into .pdf or .html files. The <code class="calibre2">Stangle()</code> function is replaced with a function that extracts the R source from a vignette.</p>
<p>R recognizes non-Sweave vignettes using filename extensions specified by the engine. For example, the <a href="https://CRAN.R-project.org/package=knitr"><strong>knitr</strong></a> package supports the extension .Rmd (standing for “R markdown”). The user indicates the vignette engine within the vignette source using a <code class="calibre2">&#92;VignetteEngine</code> line, for example</p>
<div class="example">
<pre class="example1"><code>%&#92;VignetteEngine{knitr::knitr}</code></pre>
</div>
<p>This specifies the name of a package and an engine to use in place of Sweave in processing the vignette. As <code class="calibre2">Sweave</code> is the only engine supplied with the R distribution, the package providing any other engine must be specified in the ‘VignetteBuilder’ field of the package DESCRIPTION file, and also specified in the ‘Suggests’, ‘Imports’ or ‘Depends’ field (since its namespace must be available to build or check your package). If more than one package is specified as a builder, they will be searched in the order given there. The <strong>utils</strong> package is always implicitly appended to the list of builder packages, but may be included earlier to change the search order.</p>
<p>Note that a package with non-Sweave vignettes should always have a ‘VignetteBuilder’ field in the DESCRIPTION file, since this is how <code class="calibre2">R CMD check</code> recognizes that there are vignettes to be checked: packages listed there are required when the package is checked.</p>
<p>The vignette engine can produce .tex, .pdf, or .html files as output. If it produces .tex files, R will call <code class="calibre2">texi2pdf</code> to convert them to .pdf for display to the user (unless there is a Makefile in the vignettes directory).</p>
<p>Package writers who would like to supply vignette engines need to register those engines in the package <code class="calibre2">.onLoad</code> function. For example, that function could make the call</p>
<div class="example">
<pre class="example1"><code>tools::vignetteEngine(&quot;knitr&quot;, weave = vweave, tangle = vtangle,
                      pattern = &quot;[.]Rmd&#36;&quot;, package = &quot;knitr&quot;)</code></pre>
</div>
<p>(The actual registration in <a href="https://CRAN.R-project.org/package=knitr"><strong>knitr</strong></a> is more complicated, because it supports other input formats.) See the <code class="calibre2">?tools::vignetteEngine</code> help topic for details on engine registration.</p>
<hr />
<p><a href="" id="Package-namespaces"></a> <a href="" id="Package-namespaces-1"></a></p>
<h3 id="package-namespaces" class="section">1.5 Package namespaces</h3>
<p><a href="" id="index-namespaces"></a></p>
<p>R has a namespace management system for code in packages. This system allows the package writer to specify which variables in the package should be <em>exported</em> to make them available to package users, and which variables should be <em>imported</em> from other packages.</p>
<p>The namespace for a package is specified by the NAMESPACE file in the top level package directory. This file contains <em>namespace directives</em> describing the imports and exports of the namespace. Additional directives register any shared objects to be loaded and any S3-style methods that are provided. Note that although the file looks like R code (and often has R-style comments) it is not processed as R code. Only very simple conditional processing of <code class="calibre2">if</code> statements is implemented.</p>
<p>Packages are loaded and attached to the search path by calling <code class="calibre2">library</code> or <code class="calibre2">require</code>. Only the exported variables are placed in the attached frame. Loading a package that imports variables from other packages will cause these other packages to be loaded as well (unless they have already been loaded), but they will <em>not</em> be placed on the search path by these implicit loads. Thus code in the package can only depend on objects in its own namespace and its imports (including the <strong>base</strong> namespace) being visible<a href="concept-index.html#FOOT58" id="DOCF58"><sup>58</sup></a>.</p>
<p>Namespaces are <em>sealed</em> once they are loaded. Sealing means that imports and exports cannot be changed and that internal variable bindings cannot be changed. Sealing allows a simpler implementation strategy for the namespace mechanism. Sealing also allows code analysis and compilation tools to accurately identify the definition corresponding to a global variable reference in a function body.</p>
<p>The namespace controls the search strategy for variables used by functions in the package. If not found locally, R searches the package namespace first, then the imports, then the base namespace and then the normal search path.</p>
<hr />
<p><a href="" id="Specifying-imports-and-exports"></a> <a href="" id="Specifying-imports-and-exports-1"></a></p>
<h4 id="specifying-imports-and-exports" class="subsection">1.5.1 Specifying imports and exports</h4>
<p>Exports are specified using the <code class="calibre2">export</code> directive in the NAMESPACE file. A directive of the form</p>
<p><a href="" id="index-export"></a></p>
<div class="example">
<pre class="example1"><code>export(f, g)</code></pre>
</div>
<p>specifies that the variables <code class="calibre2">f</code> and <code class="calibre2">g</code> are to be exported. (Note that variable names may be quoted, and reserved words and non-standard names such as <code class="calibre2">[&lt;-.fractions</code> must be.)</p>
<p>For packages with many variables to export it may be more convenient to specify the names to export with a regular expression using <code class="calibre2">exportPattern</code>. The directive</p>
<p><a href="" id="index-exportPattern"></a></p>
<div class="example">
<pre class="example1"><code>exportPattern(&quot;^[^&#92;&#92;.]&quot;)</code></pre>
</div>
<p>exports all variables that do not start with a period. However, such broad patterns are not recommended for production code: it is better to list all exports or use narrowly-defined groups. (This pattern applies to S4 classes.) Beware of patterns which include names starting with a period: some of these are internal-only variables and should never be exported, e.g. ‘.__S3MethodsTable__.’ (and the code nowadays excludes known cases).</p>
<p>Packages implicitly import the base namespace. Variables exported from other packages with namespaces need to be imported explicitly using the directives <code class="calibre2">import</code> and <code class="calibre2">importFrom</code>. The <code class="calibre2">import</code> directive imports all exported variables from the specified package(s). Thus the directives</p>
<p><a href="" id="index-import"></a></p>
<div class="example">
<pre class="example1"><code>import(foo, bar)</code></pre>
</div>
<p>specifies that all exported variables in the packages <strong>foo</strong> and <strong>bar</strong> are to be imported. If only some of the exported variables from a package are needed, then they can be imported using <code class="calibre2">importFrom</code>. The directive</p>
<p><a href="" id="index-importFrom"></a></p>
<div class="example">
<pre class="example1"><code>importFrom(foo, f, g)</code></pre>
</div>
<p>specifies that the exported variables <code class="calibre2">f</code> and <code class="calibre2">g</code> of the package <strong>foo</strong> are to be imported. Using <code class="calibre2">importFrom</code> selectively rather than <code class="calibre2">import</code> is good practice and recommended notably when importing from packages with more than a dozen exports.</p>
<p>To import every symbol from a package but for a few exceptions, pass the <code class="calibre2">except</code> argument to <code class="calibre2">import</code>. The directive</p>
<div class="example">
<pre class="example1"><code>import(foo, except=c(bar, baz))</code></pre>
</div>
<p>imports every symbol from <strong>foo</strong> except <code class="calibre2">bar</code> and <code class="calibre2">baz</code>. The value of <code class="calibre2">except</code> should evaluate to something coercible to a character vector, after substituting each symbol for its corresponding string.</p>
<p>It is possible to export variables from a namespace which it has imported from other namespaces: this has to be done explicitly and not <em>via</em> <code class="calibre2">exportPattern</code>.</p>
<p>If a package only needs a few objects from another package it can use a fully qualified variable reference in the code instead of a formal import. A fully qualified reference to the function <code class="calibre2">f</code> in package <strong>foo</strong> is of the form <code class="calibre2">foo::f</code>. This is slightly less efficient than a formal import and also loses the advantage of recording all dependencies in the NAMESPACE file (but they still need to be recorded in the DESCRIPTION file). Evaluating <code class="calibre2">foo::f</code> will cause package <strong>foo</strong> to be loaded, but not attached, if it was not loaded already—this can be an advantage in delaying the loading of a rarely used package.</p>
<p>Using <code class="calibre2">foo:::f</code> instead of <code class="calibre2">foo::f</code> allows access to unexported objects. This is generally not recommended, as the semantics of unexported objects may be changed by the package author in routine maintenance.</p>
<hr />
<p><a href="" id="Registering-S3-methods"></a> <a href="" id="Registering-S3-methods-1"></a></p>
<h4 id="registering-s3-methods" class="subsection">1.5.2 Registering S3 methods</h4>
<p>The standard method for S3-style <code class="calibre2">UseMethod</code> dispatching might fail to locate methods defined in a package that is imported but not attached to the search path. To ensure that these methods are available the packages defining the methods should ensure that the generics are imported and register the methods using <code class="calibre2">S3method</code> directives. If a package defines a function <code class="calibre2">print.foo</code> intended to be used as a <code class="calibre2">print</code> method for class <code class="calibre2">foo</code>, then the directive</p>
<p><a href="" id="index-S3method"></a></p>
<div class="example">
<pre class="example1"><code>S3method(print, foo)</code></pre>
</div>
<p>ensures that the method is registered and available for <code class="calibre2">UseMethod</code> dispatch, and the function <code class="calibre2">print.foo</code> does not need to be exported. Since the generic <code class="calibre2">print</code> is defined in <strong>base</strong> it does not need to be imported explicitly.</p>
<p>(Note that function and class names may be quoted, and reserved words and non-standard names such as <code class="calibre2">[&lt;-</code> and <code class="calibre2">function</code> must be.)</p>
<p>It is possible to specify a third argument to S3method, the function to be used as the method, for example</p>
<div class="example">
<pre class="example1"><code>S3method(print, check_so_symbols, .print.via.format)</code></pre>
</div>
<p>when <code class="calibre2">print.check_so_symbols</code> is not needed.</p>
<hr />
<p><a href="" id="Load-hooks"></a> <a href="" id="Load-hooks-1"></a></p>
<h4 id="load-hooks" class="subsection">1.5.3 Load hooks</h4>
<p><a href="" id="index-_002eonLoad"></a> <a href="" id="index-_002eonAttach"></a></p>
<p>There are a number of hooks called as packages are loaded, attached, detached, and unloaded. See <code class="calibre2">help(&quot;.onLoad&quot;)</code> for more details.</p>
<p>Since loading and attaching are distinct operations, separate hooks are provided for each. These hook functions are called <code class="calibre2">.onLoad</code> and <code class="calibre2">.onAttach</code>. They both take arguments<a href="concept-index.html#FOOT59" id="DOCF59"><sup>59</sup></a> <code class="calibre2">libname</code> and <code class="calibre2">pkgname</code>; they should be defined in the namespace but not exported.</p>
<p><a href="" id="index-_002eonUnload"></a> <a href="" id="index-_002eonDetach"></a> <a href="" id="index-_002eLast_002elib"></a></p>
<p>Packages can use a <code class="calibre2">.onDetach</code> or <code class="calibre2">.Last.lib</code> function (provided the latter is exported from the namespace) when <code class="calibre2">detach</code> is called on the package. It is called with a single argument, the full path to the installed package. There is also a hook <code class="calibre2">.onUnload</code> which is called when the namespace is unloaded (<em>via</em> a call to <code class="calibre2">unloadNamespace</code>, perhaps called by <code class="calibre2">detach(unload = TRUE)</code>) with argument the full path to the installed package’s directory. <code class="calibre2">.onUnload</code> and <code class="calibre2">.onDetach</code> should be defined in the namespace and not exported, but <code class="calibre2">.Last.lib</code> does need to be exported.</p>
<p>Packages are not likely to need <code class="calibre2">.onAttach</code> (except perhaps for a start-up banner); code to set options and load shared objects should be placed in a <code class="calibre2">.onLoad</code> function, or use made of the <code class="calibre2">useDynLib</code> directive described next.</p>
<p>User-level hooks are also available: see the help on function <code class="calibre2">setHook</code>.</p>
<p>These hooks are often used incorrectly. People forget to export <code class="calibre2">.Last.lib</code>. Compiled code should be loaded in <code class="calibre2">.onLoad</code> (or <em>via</em> a <code class="calibre2">useDynLb</code> directive: see below) and unloaded in <code class="calibre2">.onUnload</code>. Do remember that a package’s namespace can be loaded without the namespace being attached (e.g. by <code class="calibre2">pkgname::fun</code>) and that a package can be detached and re-attached whilst its namespace remains loaded.</p>
<hr />
<p><a href="" id="useDynLib"></a> <a href="" id="useDynLib-1"></a></p>
<h4 id="usedynlib" class="subsection">1.5.4 useDynLib</h4>
<p>A NAMESPACE file can contain one or more <code class="calibre2">useDynLib</code> directives which allows shared objects that need to be loaded.<a href="concept-index.html#FOOT60" id="DOCF60"><sup>60</sup></a> The directive</p>
<p><a href="" id="index-useDynLib"></a></p>
<div class="example">
<pre class="example1"><code>useDynLib(foo)</code></pre>
</div>
<p>registers the shared object <code class="calibre2">foo</code><a href="concept-index.html#FOOT61" id="DOCF61"><sup>61</sup></a> for loading with <code class="calibre2">library.dynam</code>. Loading of registered object(s) occurs after the package code has been loaded and before running the load hook function. Packages that would only need a load hook function to load a shared object can use the <code class="calibre2">useDynLib</code> directive instead.</p>
<p>The <code class="calibre2">useDynLib</code> directive also accepts the names of the native routines that are to be used in R <em>via</em> the <code class="calibre2">.C</code>, <code class="calibre2">.Call</code>, <code class="calibre2">.Fortran</code> and <code class="calibre2">.External</code> interface functions. These are given as additional arguments to the directive, for example,</p>
<div class="example">
<pre class="example1"><code>useDynLib(foo, myRoutine, myOtherRoutine)</code></pre>
</div>
<p>By specifying these names in the <code class="calibre2">useDynLib</code> directive, the native symbols are resolved when the package is loaded and R variables identifying these symbols are added to the package’s namespace with these names. These can be used in the <code class="calibre2">.C</code>, <code class="calibre2">.Call</code>, <code class="calibre2">.Fortran</code> and <code class="calibre2">.External</code> calls in place of the name of the routine and the <code class="calibre2">PACKAGE</code> argument. For instance, we can call the routine <code class="calibre2">myRoutine</code> from R with the code</p>
<div class="example">
<pre class="example1"><code> .Call(myRoutine, x, y)</code></pre>
</div>
<p>rather than</p>
<div class="example">
<pre class="example1"><code> .Call(&quot;myRoutine&quot;, x, y, PACKAGE = &quot;foo&quot;)</code></pre>
</div>
<p>There are at least two benefits to this approach. Firstly, the symbol lookup is done just once for each symbol rather than each time the routine is invoked. Secondly, this removes any ambiguity in resolving symbols that might be present in several compiled DLLs. However, this approach is nowadays deprecated in favour of supplying registration information (see below).</p>
<p>In some circumstances, there will already be an R variable in the package with the same name as a native symbol. For example, we may have an R function in the package named <code class="calibre2">myRoutine</code>. In this case, it is necessary to map the native symbol to a different R variable name. This can be done in the <code class="calibre2">useDynLib</code> directive by using named arguments. For instance, to map the native symbol name <code class="calibre2">myRoutine</code> to the R variable <code class="calibre2">myRoutine_sym</code>, we would use</p>
<div class="example">
<pre class="example1"><code>useDynLib(foo, myRoutine_sym = myRoutine, myOtherRoutine)</code></pre>
</div>
<p>We could then call that routine from R using the command</p>
<div class="example">
<pre class="example1"><code> .Call(myRoutine_sym, x, y)</code></pre>
</div>
<p>Symbols without explicit names are assigned to the R variable with that name.</p>
<p>In some cases, it may be preferable not to create R variables in the package’s namespace that identify the native routines. It may be too costly to compute these for many routines when the package is loaded if many of these routines are not likely to be used. In this case, one can still perform the symbol resolution correctly using the DLL, but do this each time the routine is called. Given a reference to the DLL as an R variable, say <code class="calibre2">dll</code>, we can call the routine <code class="calibre2">myRoutine</code> using the expression</p>
<div class="example">
<pre class="example1"><code> .Call(dll&#36;myRoutine, x, y)</code></pre>
</div>
<p>The <code class="calibre2">&#36;</code> operator resolves the routine with the given name in the DLL using a call to <code class="calibre2">getNativeSymbol</code>. This is the same computation as above where we resolve the symbol when the package is loaded. The only difference is that this is done each time in the case of <code class="calibre2">dll&#36;myRoutine</code>.</p>
<p>In order to use this dynamic approach (e.g., <code class="calibre2">dll&#36;myRoutine</code>), one needs the reference to the DLL as an R variable in the package. The DLL can be assigned to a variable by using the <code class="calibre2">variable = dllName</code> format used above for mapping symbols to R variables. For example, if we wanted to assign the DLL reference for the DLL <code class="calibre2">foo</code> in the example above to the variable <code class="calibre2">myDLL</code>, we would use the following directive in the NAMESPACE file:</p>
<div class="example">
<pre class="example1"><code>myDLL = useDynLib(foo, myRoutine_sym = myRoutine, myOtherRoutine)</code></pre>
</div>
<p>Then, the R variable <code class="calibre2">myDLL</code> is in the package’s namespace and available for calls such as <code class="calibre2">myDLL&#36;dynRoutine</code> to access routines that are not explicitly resolved at load time.</p>
<p>If the package has registration information (see <a href="system-and-foreign-language-interfaces.html#Registering-native-routines">Registering native routines</a>), then we can use that directly rather than specifying the list of symbols again in the <code class="calibre2">useDynLib</code> directive in the NAMESPACE file. Each routine in the registration information is specified by giving a name by which the routine is to be specified along with the address of the routine and any information about the number and type of the parameters. Using the <code class="calibre2">.registration</code> argument of <code class="calibre2">useDynLib</code>, we can instruct the namespace mechanism to create R variables for these symbols. For example, suppose we have the following registration information for a DLL named <code class="calibre2">myDLL</code>:</p>
<div class="example">
<pre class="example1"><code>static R_NativePrimitiveArgType foo_t[] = {
    REALSXP, INTSXP, STRSXP, LGLSXP
};

static const R_CMethodDef cMethods[] = {
   {&quot;foo&quot;, (DL_FUNC) &amp;foo, 4, foo_t},
   {&quot;bar_sym&quot;, (DL_FUNC) &amp;bar, 0},
   {NULL, NULL, 0, NULL}
};

static const R_CallMethodDef callMethods[] = {
   {&quot;R_call_sym&quot;, (DL_FUNC) &amp;R_call, 4},
   {&quot;R_version_sym&quot;, (DL_FUNC) &amp;R_version, 0},
   {NULL, NULL, 0}
};</code></pre>
</div>
<p>Then, the directive in the NAMESPACE file</p>
<div class="example">
<pre class="example1"><code>useDynLib(myDLL, .registration = TRUE)</code></pre>
</div>
<p>causes the DLL to be loaded and also for the R variables <code class="calibre2">foo</code>, <code class="calibre2">bar_sym</code>, <code class="calibre2">R_call_sym</code> and <code class="calibre2">R_version_sym</code> to be defined in the package’s namespace.</p>
<p>Note that the names for the R variables are taken from the entry in the registration information and do not need to be the same as the name of the native routine. This allows the creator of the registration information to map the native symbols to non-conflicting variable names in R, e.g. <code class="calibre2">R_version</code> to <code class="calibre2">R_version_sym</code> for use in an R function such as</p>
<div class="example">
<pre class="example1"><code>R_version &lt;- function()
{
  .Call(R_version_sym)
}</code></pre>
</div>
<p>Using argument <code class="calibre2">.fixes</code> allows an automatic prefix to be added to the registered symbols, which can be useful when working with an existing package. For example, package <a href="https://CRAN.R-project.org/package=KernSmooth"><strong>KernSmooth</strong></a> has</p>
<div class="example">
<pre class="example1"><code>useDynLib(KernSmooth, .registration = TRUE, .fixes = &quot;F_&quot;)</code></pre>
</div>
<p>which makes the R variables corresponding to the FORTRAN symbols <code class="calibre2">F_bkde</code> and so on, and so avoid clashes with R code in the namespace.</p>
<p><strong>NB</strong>: Using these arguments for a package which does not register native symbols merely slows down the package loading (although at the time of writing 90 CRAN packages did so). Once symbols are registered, check that the corresponding R variables are not accidentally exported by a pattern in the NAMESPACE file.</p>
<hr />
<p><a href="" id="An-example"></a> <a href="" id="An-example-1"></a></p>
<h4 id="an-example" class="subsection">1.5.5 An example</h4>
<p>As an example consider two packages named <strong>foo</strong> and <strong>bar</strong>. The R code for package <strong>foo</strong> in file foo.R is</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>x &lt;- 1
f &lt;- function(y) c(x,y)
foo &lt;- function(x) .Call(&quot;foo&quot;, x, PACKAGE=&quot;foo&quot;)
print.foo &lt;- function(x, ...) cat(&quot;&lt;a foo&gt;&#92;n&quot;)</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>Some C code defines a C function compiled into DLL <code class="calibre2">foo</code> (with an appropriate extension). The NAMESPACE file for this package is</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>useDynLib(foo)
export(f, foo)
S3method(print, foo)</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>The second package <strong>bar</strong> has code file bar.R</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>c &lt;- function(...) sum(...)
g &lt;- function(y) f(c(y, 7))
h &lt;- function(y) y+9</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>and NAMESPACE file</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>import(foo)
export(g, h)</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>Calling <code class="calibre2">library(bar)</code> loads <strong>bar</strong> and attaches its exports to the search path. Package <strong>foo</strong> is also loaded but not attached to the search path. A call to <code class="calibre2">g</code> produces</p>
<div class="example">
<pre class="example1"><code>&gt; g(6)
[1]  1 13</code></pre>
</div>
<p>This is consistent with the definitions of <code class="calibre2">c</code> in the two settings: in <strong>bar</strong> the function <code class="calibre2">c</code> is defined to be equivalent to <code class="calibre2">sum</code>, but in <strong>foo</strong> the variable <code class="calibre2">c</code> refers to the standard function <code class="calibre2">c</code> in <strong>base</strong>.</p>
<hr />
<p><a href="" id="Namespaces-with-S4-classes-and-methods"></a> <a href="" id="Namespaces-with-S4-classes-and-methods-1"></a></p>
<h4 id="namespaces-with-s4-classes-and-methods" class="subsection">1.5.6 Namespaces with S4 classes and methods</h4>
<p>Some additional steps are needed for packages which make use of formal (S4-style) classes and methods (unless these are purely used internally). The package should have <code class="calibre2">Depends: methods</code> in its DESCRIPTION file<a href="concept-index.html#FOOT62" id="DOCF62"><sup>62</sup></a> and <code class="calibre2">import(methods)</code> or <code class="calibre2">importFrom(methods, ...)</code> plus any classes and methods which are to be exported need to be declared in the NAMESPACE file. For example, the <strong>stats4</strong> package has</p>
<p><a href="" id="index-exportClasses"></a> <a href="" id="index-exportMethods"></a></p>
<div class="example">
<pre class="example1"><code>export(mle) # exporting methods implicitly exports the generic
importFrom(&quot;graphics&quot;, plot)
importFrom(&quot;stats&quot;, optim, qchisq)
## For these, we define methods or (AIC, BIC, nobs) an implicit generic:
importFrom(&quot;stats&quot;, AIC, BIC, coef, confint, logLik, nobs, profile,
           update, vcov)
exportClasses(mle, profile.mle, summary.mle)
## All methods for imported generics:
exportMethods(coef, confint, logLik, plot, profile, summary,
              show, update, vcov)
## implicit generics which do not have any methods here
export(AIC, BIC, nobs)</code></pre>
</div>
<p><a href="" id="index-exportPattern-1"></a> <a href="" id="index-exportClassPattern"></a></p>
<p>All S4 classes to be used outside the package need to be listed in an <code class="calibre2">exportClasses</code> directive. Alternatively, they can be specified using <code class="calibre2">exportClassPattern</code><a href="concept-index.html#FOOT63" id="DOCF63"><sup>63</sup></a> in the same style as for <code class="calibre2">exportPattern</code>. To export methods for generics from other packages an <code class="calibre2">exportMethods</code> directive can be used.</p>
<p>Note that exporting methods on a generic in the namespace will also export the generic, and exporting a generic in the namespace will also export its methods. If the generic function is not local to this package, either because it was imported as a generic function or because the non-generic version has been made generic solely to add S4 methods to it (as for functions such as <code class="calibre2">plot</code> in the example above), it can be declared <em>via</em> either or both of <code class="calibre2">export</code> or <code class="calibre2">exportMethods</code>, but the latter is clearer (and is used in the <strong>stats4</strong> example above). In particular, for primitive functions there is no generic function, so <code class="calibre2">export</code> would export the primitive, which makes no sense. On the other hand, if the generic is local to this package, it is more natural to export the function itself using <code class="calibre2">export()</code>, and this <em>must</em> be done if an implicit generic is created without setting any methods for it (as is the case for <code class="calibre2">AIC</code> in <strong>stats4</strong>).</p>
<p>A non-local generic function is only exported to ensure that calls to the function will dispatch the methods from this package (and that is not done or required when the methods are for primitive functions). For this reason, you do not need to document such implicitly created generic functions, and <code class="calibre2">undoc</code> in package <strong>tools</strong> will not report them.</p>
<p>If a package uses S4 classes and methods exported from another package, but does not import the entire namespace of the other package<a href="concept-index.html#FOOT64" id="DOCF64"><sup>64</sup></a>, it needs to import the classes and methods explicitly, with directives</p>
<p><a href="" id="index-importClassesFrom"></a> <a href="" id="index-importMethodsFrom"></a></p>
<div class="example">
<pre class="example1"><code>importClassesFrom(package, ...)
importMethodsFrom(package, ...)</code></pre>
</div>
<p>listing the classes and functions with methods respectively. Suppose we had two small packages <strong>A</strong> and <strong>B</strong> with <strong>B</strong> using <strong>A</strong>. Then they could have <code class="calibre2">NAMESPACE</code> files</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>export(f1, ng1)
exportMethods(&quot;[&quot;)
exportClasses(c1)</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>and</p>
<blockquote>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><div class="example">
<pre class="example1"><code>importFrom(A, ng1)
importClassesFrom(A, c1)
importMethodsFrom(A, f1)
export(f4, f5)
exportMethods(f6, &quot;[&quot;)
exportClasses(c1, c2)</code></pre>
</div></td>
</tr>
</tbody>
</table>
</blockquote>
<p>respectively.</p>
<p>Note that <code class="calibre2">importMethodsFrom</code> will also import any generics defined in the namespace on those methods.</p>
<p>It is important if you export S4 methods that the corresponding generics are available. You may for example need to import <code class="calibre2">plot</code> from <strong>graphics</strong> to make visible a function to be converted into its implicit generic. But it is better practice to make use of the generics exported by <strong>stats4</strong> as this enables multiple packages to unambiguously set methods on those generics.</p>
<hr />
<p><a href="" id="Writing-portable-packages"></a> <a href="" id="Writing-portable-packages-1"></a></p>
<h3 id="writing-portable-packages" class="section">1.6 Writing portable packages</h3>
<p>This section contains advice on writing packages to be used on multiple platforms or for distribution (for example to be submitted to a package repository such as CRAN).</p>
<p>Portable packages should have simple file names: use only alphanumeric ASCII characters and period (<code class="calibre2">.</code>), and avoid those names not allowed under Windows which are mentioned above.</p>
<p>Many of the graphics devices are platform-specific: even <code class="calibre2">X11()</code> (aka <code class="calibre2">x11()</code>) which although emulated on Windows may not be available on a Unix-alike (and is not the preferred screen device on OS X). It is rarely necessary for package code or examples to open a new device, but if essential,<a href="concept-index.html#FOOT65" id="DOCF65"><sup>65</sup></a> use <code class="calibre2">dev.new()</code>.</p>
<p>Use <code class="calibre2">R CMD build</code> to make the release .tar.gz file.</p>
<p><code class="calibre2">R CMD check</code> provides a basic set of checks, but often further problems emerge when people try to install and use packages submitted to CRAN – many of these involve compiled code. Here are some further checks that you can do to make your package more portable.</p>
<ul>
<li>If your package has a configure script, provide a configure.win script to be used on Windows (an empty file if no actions are needed).</li>
<li><p>If your package has a Makevars or Makefile file, make sure that you use only portable make features. Such files should be LF-terminated<a href="concept-index.html#FOOT66" id="DOCF66"><sup>66</sup></a> (including the final line of the file) and not make use of GNU extensions. (The POSIX specification is available at <a href="http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html" class="uri">http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html</a>; anything not documented there should be regarded as an extension to be avoided.) Commonly misused GNU extensions are conditional inclusions (<code class="calibre2">ifeq</code> and the like), <code class="calibre2">&#36;{shell ...}</code>, <code class="calibre2">&#36;{wildcard ...}</code> and similar, and the use of <code class="calibre2">+=</code><a href="concept-index.html#FOOT67" id="DOCF67"><sup>67</sup></a> and <code class="calibre2">:=</code>. Also, the use of <code class="calibre2">&#36;&lt;</code> other than in implicit rules is a GNU extension, as is the <code class="calibre2">&#36;^</code> macro. Unfortunately makefiles which use GNU extensions often run on other platforms but do not have the intended results.</p>
<p>The use of <code class="calibre2">&#36;{shell ...}</code> can be avoided by using backticks, e.g.</p>
<div class="example">
<pre class="example1"><code>PKG_CPPFLAGS = `gsl-config --cflags`</code></pre>
</div>
<p>which works in all versions of <code class="calibre2">make</code> known<a href="concept-index.html#FOOT68" id="DOCF68"><sup>68</sup></a> to be used with R.</p>
<p>If you really must require GNU make, declare it in the DESCRIPTION file by</p>
<div class="example">
<pre class="example1"><code>SystemRequirements: GNU make</code></pre>
</div>
<p>and ensure that you use the value of environment variable <code class="calibre2">MAKE</code> (and not just <code class="calibre2">make</code>) in your scripts. (On some platforms GNU make is available under a name such as <code class="calibre2">gmake</code>, and there <code class="calibre2">SystemRequirements</code> is used to set <code class="calibre2">MAKE</code>.)</p>
<p>If you only need GNU make for parts of the package which are rarely needed (for example to create bibliography files under vignettes), use a file called GNUmakefile rather than Makefile as GNU make (only) will use the former.</p>
<p>Since the only viable make for Windows is GNU make, it is permissible to use GNU extensions in files Makevars.win or Makefile.win.</p></li>
<li><p>Bash extensions also need to be avoided in shell scripts, including expressions in Makefiles (which are passed to the shell for processing). Some R platforms use strict<a href="concept-index.html#FOOT69" id="DOCF69"><sup>69</sup></a> Bourne shells: the R toolset on Windows and some Unix-alike OSes use <code class="calibre2">ash</code> (<a href="https://en.wikipedia.org/wiki/Almquist_shell" class="uri">https://en.wikipedia.org/wiki/Almquist_shell</a>), a rather minimal shell with few builtins. Beware of assuming that all the POSIX command-line utilities are available, especially on Windows where only a minimal set is provided for use with R. One particular issue is the use of <code class="calibre2">echo</code>, for which two behaviours are allowed (<a href="http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html" class="uri">http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html</a>) and both occur as defaults on R platforms: portable applications should not use -n (as the first argument) nor escape sequences. Another common issue is the construction</p>
<div class="example">
<pre class="example1"><code>export FOO=value</code></pre>
</div>
<p>which is bash-specific (first set the variable then export it by name).</p></li>
<li><p>Make use of the abilities of your compilers to check the standards-conformance of your code. For example, <code class="calibre2">gcc</code> and <code class="calibre2">gfortran</code><a href="concept-index.html#FOOT70" id="DOCF70"><sup>70</sup></a> can be used with options -Wall -pedantic to alert you to potential problems. This is particularly important for C++, where <code class="calibre2">g++ -Wall -pedantic</code> will alert you to the use of some of the GNU extensions which fail to compile on most other C++ compilers. If R was not configured accordingly, one can achieve this <em>via</em> personal Makevars files.</p>
<p>Portable C++ code needs to follow the 1998 standard (and not use features from C99), or to specify a C++11 compiler (see <a href="creating-r-packages.html#Using-C_002b_002b11-code">Using C++11 code</a>) where available (which is not the case on all R platforms).</p>
<p>If you use FORTRAN 77, <code class="calibre2">ftnchek</code> (<a href="http://www.dsm.fordham.edu/~ftnchek/" class="uri">http://www.dsm.fordham.edu/~ftnchek/</a>) provides thorough testing of conformance to the standard.</p>
<p>If using Fortran 9x with the GNU compiler, use the flags -std=f95 -Wall -pedantic which reject most GNU extensions and features from later standards.</p>
<p>R has tested that <code class="calibre2">DOUBLE COMPLEX</code> works (although an extension to the Fortran standards) and so is preferred to <code class="calibre2">COMPLEX*16</code>. (Fortran 9x code can use something like <code class="calibre2">COMPLEX(KIND=KIND(0.0D0))</code><a href="concept-index.html#FOOT71" id="DOCF71"><sup>71</sup></a>.)</p>
<p>Not all common R platforms conform to the expected standards, e.g. C99 for C code. One common area of problems is the <code class="calibre2">*printf</code> functions where Windows does not support <code class="calibre2">%lld</code>, <code class="calibre2">%Lf</code> and similar formats (and has its own formats such as <code class="calibre2">%I64d</code> for 64-bit integers). It is very rare to need to output such types, and 64-bit integers can usually be converted to doubles for output.</p></li>
<li><p><code class="calibre2">R CMD check</code> performs some checks for non-portable compiler/linker flags in src/Makevars. However, it cannot check the meaning of such flags, and some are commonly accepted but with compiler-specific meanings. There are other non-portable flags which are not checked, nor are src/Makefile files and makefiles in sub-directories. As a comment in the code says</p>
<blockquote>
<p>It is hard to think of anything apart from -I* and -D* that is safe for general use …</p>
</blockquote>
<p>although -pthread is pretty close to portable. (Option -U is portable but little use on the command line as it will only cancel built-in defines (not portable) and those defined earlier on the command line (R does not use any).)</p></li>
<li><p>Do be very careful with passing arguments between R, C and FORTRAN code. In particular, <code class="calibre2">long</code> in C will be 32-bit on some R platforms (including 64-bit Windows), but 64-bit on most modern Unix and Linux platforms. It is rather unlikely that the use of <code class="calibre2">long</code> in C code has been thought through: if you need a longer type than <code class="calibre2">int</code> you should use a configure test for a C99/C++11 type such as <code class="calibre2">int_fast64_t</code> (and failing that, <code class="calibre2">long long</code> <a href="concept-index.html#FOOT72" id="DOCF72"><sup>72</sup></a>) and typedef your own type to be <code class="calibre2">long</code> or <code class="calibre2">long long</code>, or use another suitable type (such as <code class="calibre2">size_t</code>).</p>
<p>It is not safe to assume that <code class="calibre2">long</code> and pointer types are the same size, and they are not on 64-bit Windows. If you need to convert pointers to and from integers use the C99/C++11 integer types <code class="calibre2">intptr_t</code> and <code class="calibre2">uintptr_t</code> (which are defined in the header <code class="calibre2">&lt;stdint.h&gt;</code> and are not required to be implemented by the C99 standard but are used in C code by R itself).</p>
<p>Note that <code class="calibre2">integer</code> in FORTRAN corresponds to <code class="calibre2">int</code> in C on all R platforms.</p></li>
<li><p>Under no circumstances should your compiled code ever call <code class="calibre2">abort</code> or <code class="calibre2">exit</code><a href="concept-index.html#FOOT73" id="DOCF73"><sup>73</sup></a>: these terminate the user’s R process, quite possibly including all his unsaved work. One usage that could call <code class="calibre2">abort</code> is the <code class="calibre2">assert</code> macro in C or C++ functions, which should never be active in production code. The normal way to ensure that is to define the macro <code class="calibre2">NDEBUG</code>, and <code class="calibre2">R CMD INSTALL</code> does so as part of the compilation flags. If you wish to use <code class="calibre2">assert</code> during development. you can include <code class="calibre2">-UNDEBUG</code> in <code class="calibre2">PKG_CPPFLAGS</code>. Note that your own src/Makefile or makefiles in sub-directories may also need to define <code class="calibre2">NDEBUG</code>.</p>
<p>This applies not only to your own code but to any external software you compile in or link to.</p></li>
<li>Compiled code should not write to stdout or stderr and C++ and Fortran I/O should not be used. As with the previous item such calls may come from external software and may never be called, but package authors are often mistaken about that.</li>
<li><p>Compiled code should not call the system random number generators such as <code class="calibre2">rand</code>, <code class="calibre2">drand48</code> and <code class="calibre2">random</code><a href="concept-index.html#FOOT74" id="DOCF74"><sup>74</sup></a>, but rather use the interfaces to R’s RNGs described in <a href="the-r-api:-entry-points-for-c-code.html#Random-numbers">Random numbers</a>. In particular, if more than one package initializes the system RNG (e.g. <em>via</em> <code class="calibre2">srand</code>), they will interfere with each other.</p>
<p>Nor should the C++11 random number library be used.</p></li>
<li>Errors in memory allocation and reading/writing outside arrays are very common causes of crashes (e.g., segfaults) on some machines. See <a href="debugging.html#Checking-memory-access">Checking memory access</a> for tools which can be used to look for this.</li>
<li><p>Many platforms will allow unsatisfied entry points in compiled code, but will crash the application (here R) if they are ever used. Some (notably Windows) will not. Looking at the output of</p>
<div class="example">
<pre class="example1"><code>nm -pg mypkg.so</code></pre>
</div>
<p>and checking if any of the symbols marked <code class="calibre2">U</code> is unexpected is a good way to avoid this.</p></li>
<li>Linkers have a lot of freedom in how to resolve entry points in dynamically-loaded code, so the results may differ by platform. One area that has caused grief is packages including copies of standard system software such as <code class="calibre2">libz</code> (especially those already linked into R). In the case in point, entry point <code class="calibre2">gzgets</code> was sometimes resolved against the old version compiled into the package, sometimes against the copy compiled into R and sometimes against the system dynamic library. The only safe solution is to rename the entry points in the copy in the package. We have even seen problems with entry point name <code class="calibre2">myprintf</code>, which is a system entry point<a href="concept-index.html#FOOT75" id="DOCF75"><sup>75</sup></a> on some Linux systems.</li>
<li>Conflicts between symbols in DLLs are handled in very platform-specific ways. Good ways to avoid trouble are to make as many symbols as possible static (check with <code class="calibre2">nm -pg</code>), and to use names which are clearly tied to your package (which also helps users if anything does go wrong). Note that symbol names starting with <code class="calibre2">R_</code> are regarded as part of R’s namespace and should not be used in packages.</li>
<li>It is good practice for DLLs to register their symbols (see <a href="system-and-foreign-language-interfaces.html#Registering-native-routines">Registering native routines</a>), restrict visibility (see <a href="the-r-api:-entry-points-for-c-code.html#Controlling-visibility">Controlling visibility</a>) and not allow symbol search (see <a href="system-and-foreign-language-interfaces.html#Registering-native-routines">Registering native routines</a>). It should be possible for a DLL to have only one visible symbol, <code class="calibre2">R_init_pkgname</code>, on suitable platforms<a href="concept-index.html#FOOT76" id="DOCF76"><sup>76</sup></a>, which would completely avoid symbol conflicts.</li>
<li>It is not portable to call compiled code in R or other packages <em>via</em> <code class="calibre2">.Internal</code>, <code class="calibre2">.C</code>, <code class="calibre2">.Fortran</code>, <code class="calibre2">.Call</code> or <code class="calibre2">.External</code>, since such interfaces are subject to change without notice and will probably result in your code terminating the R process.</li>
<li>Do not use (hard or symbolic) file links in your package sources. Where possible <code class="calibre2">R CMD build</code> will replace them by copies.</li>
<li>If you do not yourself have a Windows system, consider submitting your source package to WinBuilder (<a href="https://win-builder.r-project.org/" class="uri">https://win-builder.r-project.org/</a>) before distribution.</li>
<li>It is bad practice for package code to alter the search path using <code class="calibre2">library</code>, <code class="calibre2">require</code> or <code class="calibre2">attach</code> and this often does not work as intended. For alternatives, see <a href="creating-r-packages.html#Suggested-packages">Suggested packages</a> and <code class="calibre2">with</code>.</li>
<li>Examples can be run interactively <em>via</em> <code class="calibre2">example</code> as well as in batch mode when checking. So they should behave appropriately in both scenarios, conditioning by <code class="calibre2">interactive()</code> the parts which need an operator or observer. For instance, progress bars<a href="concept-index.html#FOOT77" id="DOCF77"><sup>77</sup></a> are only appropriate in interactive use, as is displaying help pages or calling <code class="calibre2">View()</code> (see below).</li>
<li>Be careful with the order of entries in macros such as <code class="calibre2">PKG_LIBS</code>. Some linkers will re-order the entries, and behaviour can differ between dynamic and static libraries. Generally -L options should precede<a href="concept-index.html#FOOT78" id="DOCF78"><sup>78</sup></a> the libraries (typically specified by -l options) to be found from those directories, and libraries are searched once in the order they are specified. Not all linkers allow a space after -L .</li>
<li><p>Care is needed with the use of <code class="calibre2">LinkingTo</code>. This puts one or more directories on the include search path ahead of system headers but (prior to R 3.4.0) after those specified in the <code class="calibre2">CPPFLAGS</code> macro of the R build (which normally includes <code class="calibre2">-I/usr/local/include</code>, but most platforms ignore that and include it with the system headers).</p>
<p>Any confusion would be avoided by having <code class="calibre2">LinkingTo</code> headers in a directory named after the package. In any case, name conflicts of headers and directories under package include directories should be avoided, both between packages and between a package and system and third-party software.</p></li>
<li>The <code class="calibre2">ar</code> utility is often used in makefiles to make static libraries. Its modifier <code class="calibre2">u</code> is defined by POSIX but is disabled in GNU <code class="calibre2">ar</code> on some recent Linux distributions which use ‘deterministic mode’. The safest way to make a static library is to first remove any existing file of that name then use <code class="calibre2">ar -cr</code> and then <code class="calibre2">ranlib</code> if needed (which is system-dependent: on most systems<a href="concept-index.html#FOOT79" id="DOCF79"><sup>79</sup></a> <code class="calibre2">ar</code> always maintains a symbol table). The POSIX standard says options should be preceded by a hyphen (as in -cr), although most OSes accept them without. Note that on some systems <code class="calibre2">ar -cr</code> must have at least one file specified.</li>
<li>Some people have a need to set a locale. Locale names are not portable, and e.g. ‘fr_FR.utf8’ is commonly used on Linux but not accepted on either Solaris or macOS. ‘fr_FR.UTF-8’ is more portable, being accepted on recent Linux, AIX, FreeBSD, macOS and Solaris (at least). However, some Linux distributions micro-package, so locales defined by <strong>glibc</strong> (including these examples) may not be installed.</li>
<li><p>Avoid spaces in file names, not least as they can cause difficulties for external tools. A recent example was a package with a <a href="https://CRAN.R-project.org/package=knitr"><strong>knitr</strong></a> vignette that used spaces in plot names: this caused some versions of <code class="calibre2">pandoc</code> to fail with a baffling error message.</p>
<p>Non-ASCII filenames can also cause problems (particularly in non-UTF-8 locales).</p></li>
<li><p>Make sure that any version requirement for Java code is both declared in the ‘SystemRequirements’ field and tested at runtime (not least as the Java installation when the package is installed might not be the same as when the package is run and will not be for binary packages). Java 8 (aka 1.8) is available for fewer platforms than Java 7. A suitable test for packages using <a href="https://CRAN.R-project.org/package=rJava"><strong>rJava</strong></a> would be</p>
<div class="example">
<pre class="example1"><code>.jinit()
jv &lt;- .jcall(&quot;java/lang/System&quot;, &quot;S&quot;, &quot;getProperty&quot;, &quot;java.runtime.version&quot;)
jvn &lt;- as.numeric(paste0(strsplit(jv, &quot;[.]&quot;)[[1L]][1:2], collapse = &quot;.&quot;))
if(jvn &lt; 1.8) stop(&quot;Java 8 is needed for this package but not available&quot;)</code></pre>
</div>
<p>Some packages have stated a requirement on a particular JDK, but a package should only be requiring a JRE unless providing its own Java interface.</p></li>
<li><p>A package with a hard-to-satisfy system requirement is by definition not portable, annoyingly so if this is not declared in the ‘SystemRequirements’ field. The most common example is the use of <code class="calibre2">pandoc</code>, which is only available for a very limited range of platforms (and has onerous requirements to install from source) and has capabilities<a href="concept-index.html#FOOT80" id="DOCF80"><sup>80</sup></a> that vary by build but are not documented.</p>
<p>An external command can be an optional requirement for an imported package but needed for examples or tests in the package itself. Such usage should always be conditional on a test for existence (perhaps using <code class="calibre2">Sys.which</code>), as well as declared in the ‘SystemRequirements’ field.</p></li>
<li>Be sure to use portable encoding names: none of <code class="calibre2">utf8</code>, <code class="calibre2">mac</code> and <code class="calibre2">macroman</code> are. See the help for <code class="calibre2">file</code> for more details.</li>
<li><p>Do not invoke R by plain <code class="calibre2">R</code>, <code class="calibre2">Rscript</code> or (on Windows) <code class="calibre2">Rterm</code> in your examples, tests, vignettes, makefiles or other scripts. As pointed out in several places earlier in this manual, use something like</p>
<div class="example">
<pre class="example1"><code>&quot;&#36;(R_HOME)/bin/Rscript&quot;
&quot;&#36;(R_HOME)/bin&#36;(R_ARCH_BIN)/Rterm&quot;</code></pre>
</div>
<p>with appropriate quotes (as, although not recommended, <code class="calibre2">R_HOME</code> can contain spaces).</p></li>
</ul>
<p>Do be careful in what your tests (and examples) actually test. Bad practice seen in distributed packages include:</p>
<ul>
<li>It is not reasonable to test the time taken by a command: you cannot know how fast or how heavily loaded an R platform might be. At best you can test a ratio of times, and even that is fraught with difficulties.</li>
<li><p>Do not test the exact format of R messages (from R itself or from other packages): They change, and they can be translated.</p>
<p>Packages have even tested the exact format of system error messages, which are platform-dependent and perhaps locale-dependent.</p></li>
<li>If you use functions such as <code class="calibre2">View</code>, remember that in testing there is no one to look at the output. It is better to use something like one of
<div class="example">
<pre class="example1"><code>if(interactive()) View(obj) else print(head(obj))
if(interactive()) View(obj) else str(obj)</code></pre>
</div></li>
<li><p>Only test the accuracy of results if you have done a formal error analysis. Things such as checking that probabilities numerically sum to one are silly: numerical tests should always have a tolerance. That the tests on your platform achieve a particular tolerance says little about other platforms. R is configured by default to make use of long doubles where available, but they may not be available or be too slow for routine use. Most R platforms use ‘ix86’ or ‘x86_64’ CPUs: these use extended precision registers on some but not all of their FPU instructions. Thus the achieved precision can depend on the compiler version and optimization flags—our experience is that 32-bit builds tend to be less precise than 64-bit ones. But not all platforms use those CPUs, and not all<a href="concept-index.html#FOOT81" id="DOCF81"><sup>81</sup></a> which use them configure them to allow the use of extended precision. In particular, ARM CPUs do not (currently) have extended precision nor long doubles, and long double was 64-bit on HP/PA Linux.</p>
<p>If you must try to establish a tolerance empirically, configure and build R with --disable-long-double and use appropriate compiler flags (such as -ffloat-store and -fexcess-precision=standard for <code class="calibre2">gcc</code>, depending on the CPU type<a href="concept-index.html#FOOT82" id="DOCF82"><sup>82</sup></a>) to mitigate the effects of extended-precision calculations.</p>
<p>Tests which involve random inputs or non-deterministic algorithms should normally set a seed or be tested for many seeds.</p></li>
</ul>
<hr />
<p><a href="" id="PDF-size"></a> <a href="" id="PDF-size-1"></a></p>
<h4 id="pdf-size" class="subsection">1.6.1 PDF size</h4>
<p>There are a several tools available to reduce the size of PDF files: often the size can be reduced substantially with no or minimal loss in quality. Not only do large files take up space: they can stress the PDF viewer and take many minutes to print (if they can be printed at all).</p>
<p><code class="calibre2">qpdf</code> (<a href="http://qpdf.sourceforge.net/" class="uri">http://qpdf.sourceforge.net/</a>) can compress losslessly. It is fairly readily available (e.g. it has binaries for Windows and packages in Debian/Ubuntu/Fedora, and is installed as part of the CRAN macOS distribution of R). <code class="calibre2">R CMD build</code> has an option to run <code class="calibre2">qpdf</code> over PDF files under inst/doc and replace them if at least 10Kb and 10% is saved. The full path to the <code class="calibre2">qpdf</code> command can be supplied as environment variable <code class="calibre2">R_QPDF</code> (and is on the CRAN binary of R for macOS). It seems MiKTeX does not use PDF object compression and so <code class="calibre2">qpdf</code> can reduce considerably the files it outputs: MiKTeX can be overridden by code in the preamble of an Sweave or LaTeX file — see how this is done for the R reference manual at <a href="https://svn.r-project.org/R/trunk/doc/manual/refman.top" class="uri">https://svn.r-project.org/R/trunk/doc/manual/refman.top</a>.</p>
<p>Other tools can reduce the size of PDFs containing bitmap images at excessively high resolution. These are often best re-generated (for example <code class="calibre2">Sweave</code> defaults to 300 ppi, and 100–150 is more appropriate for a package manual). These tools include Adobe Acrobat (not Reader), Apple’s Preview<a href="concept-index.html#FOOT83" id="DOCF83"><sup>83</sup></a> and Ghostscript (which converts PDF to PDF by</p>
<div class="example">
<pre class="example1"><code>ps2pdf options -dAutoRotatePages=/None in.pdf out.pdf</code></pre>
</div>
<p>and suitable options might be</p>
<div class="example">
<pre class="example1"><code>-dPDFSETTINGS=/ebook
-dPDFSETTINGS=/screen</code></pre>
</div>
<p>; see <a href="http://www.ghostscript.com/doc/current/Ps2pdf.htm" class="uri">http://www.ghostscript.com/doc/current/Ps2pdf.htm</a> for more such and consider all the options for image downsampling). There have been examples in CRAN packages for which Ghostscript 9.06 and later produced much better reductions than 9.05 or earlier.</p>
<p>We come across occasionally large PDF files containing excessively complicated figures using PDF vector graphics: such figures are often best redesigned or failing that, output as PNG files.</p>
<p>Option --compact-vignettes to <code class="calibre2">R CMD build</code> defaults to value ‘qpdf’: use ‘both’ to try harder to reduce the size, provided you have Ghostscript available (see the help for <code class="calibre2">tools::compactPDF</code>).</p>
<hr />
<p><a href="" id="Check-timing"></a> <a href="" id="Check-timing-1"></a></p>
<h4 id="check-timing" class="subsection">1.6.2 Check timing</h4>
<p>There are several ways to find out where time is being spent in the check process. Start by setting the environment variable <code class="calibre2">_R_CHECK_TIMINGS_</code> to ‘0’. This will report the total CPU times (not Windows) and elapsed times for installation and running examples, tests and vignettes, under each sub-architecture if appropriate. For tests and vignettes, it reports the time for each as well as the total.</p>
<p>Setting <code class="calibre2">_R_CHECK_TIMINGS_</code> to a positive value sets a threshold (in seconds elapsed time) for reporting timings.</p>
<p>If you need to look in more detail at the timings for examples, use option --timings to <code class="calibre2">R CMD check</code> (this is set by --as-cran). This adds a summary to the check output for all the examples with CPU or elapsed time of more than 5 seconds. It produces a file mypkg.Rcheck/mypkg-Ex.timings containing timings for each help file: it is a tab-delimited file which can be read into R for further analysis.</p>
<p>Timings for the tests and vignette runs are given at the bottom of the corresponding log file: note that log files for successful vignette runs are only retained if environment variable <code class="calibre2">_R_CHECK_ALWAYS_LOG_VIGNETTE_OUTPUT_</code> is set to a true value.</p>
<hr />
<p><a href="" id="Encoding-issues"></a> <a href="" id="Encoding-issues-1"></a></p>
<h4 id="encoding-issues" class="subsection">1.6.3 Encoding issues</h4>
<p>Care is needed if your package contains non-ASCII text, and in particular if it is intended to be used in more than one locale. It is possible to mark the encoding used in the DESCRIPTION file and in .Rd files, as discussed elsewhere in this manual.</p>
<p>First, consider carefully if you really need non-ASCII text. Many users of R will only be able to view correctly text in their native language group (e.g. Western European, Eastern European, Simplified Chinese) and ASCII.<a href="concept-index.html#FOOT84" id="DOCF84"><sup>84</sup></a>. Other characters may not be rendered at all, rendered incorrectly, or cause your R code to give an error. For .Rd documentation, marking the encoding and including ASCII transliterations is likely to do a reasonable job. The set of characters which is commonly supported is wider than it used to be around 2000, but non-Latin alphabets (Greek, Russian, Georgian, …) are still often problematic and those with double-width characters (Chinese, Japanese, Korean) often need specialist fonts to render correctly.</p>
<p>Several CRAN packages have messages in their R code in French (and a few in German). A better way to tackle this is to use the internationalization facilities discussed elsewhere in this manual.</p>
<p>Function <code class="calibre2">showNonASCIIfile</code> in package <strong>tools</strong> can help in finding non-ASCII bytes in files.</p>
<p>There is a portable way to have arbitrary text in character strings (only) in your R code, which is to supply them in Unicode as <code class="calibre2">&#92;uxxxx</code> escapes. If there are any characters not in the current encoding the parser will encode the character string as UTF-8 and mark it as such. This applies also to character strings in datasets: they can be prepared using <code class="calibre2">&#92;uxxxx</code> escapes or encoded in UTF-8 in a UTF-8 locale, or even converted to UTF-8 via ‘iconv()’. If you do this, make sure you have ‘R (&gt;= 2.10)’ (or later) in the ‘Depends’ field of the DESCRIPTION file.</p>
<p>R sessions running in non-UTF-8 locales will if possible re-encode such strings for display (and this is done by <code class="calibre2">RGui</code> on Windows, for example). Suitable fonts will need to be selected or made available<a href="concept-index.html#FOOT85" id="DOCF85"><sup>85</sup></a> both for the console/terminal and graphics devices such as ‘X11()’ and ‘windows()’. Using ‘postscript’ or ‘pdf’ will choose a default 8-bit encoding depending on the language of the UTF-8 locale, and your users would need to be told how to select the ‘encoding’ argument.</p>
<p>If you want to run <code class="calibre2">R CMD check</code> on a Unix-alike over a package that sets a package encoding in its DESCRIPTION file <em>and do not use a UTF-8 locale</em> you may need to specify a suitable locale <em>via</em> environment variable <code class="calibre2">R_ENCODING_LOCALES</code>. The default is equivalent to the value</p>
<div class="example">
<pre class="example1"><code>&quot;latin1=en_US:latin2=pl_PL:UTF-8=en_US.UTF-8:latin9=fr_FR.iso885915@euro&quot;</code></pre>
</div>
<p>(which is appropriate for a system based on <code class="calibre2">glibc</code>: macOS requires <code class="calibre2">latin9=fr_FR.ISO8859-15</code>) except that if the current locale is UTF-8 then the package code is translated to UTF-8 for syntax checking, so it is strongly recommended to check in a UTF-8 locale.</p>
<hr />
<p><a href="" id="Portable-C-and-C_002b_002b-code"></a> <a href="" id="Portable-C-and-C_002b_002b-code-1"></a></p>
<h4 id="portable-c-and-c-code" class="subsection">1.6.4 Portable C and C++ code</h4>
<p>Writing portable C and C++ code is mainly a matter of observing the standards (C99, C++98 or where declared C++11/14) and testing that extensions (such as POSIX functions) are supported.</p>
<p>Note that the ‘TR1’ C++ extensions are not part of any of these standards and the <code class="calibre2">&lt;tr1/name&gt;</code> headers are not supplied by some of the compilers used for R, including on macOS. (Use the C++11 versions instead.)</p>
<p>Note too that the POSIX standards only require recently-defined functions to be declared if certain macros are defined with large enough values, and on some compiler/OS combinations<a href="concept-index.html#FOOT86" id="DOCF86"><sup>86</sup></a> they are not declared otherwise. So you may need to include something like one of <a href="concept-index.html#FOOT87" id="DOCF87"><sup>87</sup></a></p>
<div class="example">
<pre class="example1"><code>#define _XOPEN_SOURCE 500</code></pre>
</div>
<p>or</p>
<div class="example">
<pre class="example1"><code>#ifdef __GLIBC__
# define _POSIX_C_SOURCE 200809L
#endif</code></pre>
</div>
<p>before <em>any</em> headers. (<code class="calibre2">strdup</code> and <code class="calibre2">strncasecmp</code> are two such functions.)</p>
<p>However, some common errors are worth pointing out here. It can be helpful to look up functions at <a href="http://www.cplusplus.com/reference/" class="uri">http://www.cplusplus.com/reference/</a> or <a href="http://en.cppreference.com/w/" class="uri">http://en.cppreference.com/w/</a> and compare what is defined in the various standards.</p>
<p>Both the compiler and OS (<em>via</em> system header files, which may differ by architecture even for nominally the same OS) affect the compilability of C/C++ code. Compilers from the GCC, <code class="calibre2">clang</code>, Intel and Oracle Studio suites are routinely used with R, and both <code class="calibre2">clang</code> and Oracle have more than one implementation of C++ headers and library. The range of possibilities makes comprehensive empirical checking impossible, and regrettably compilers are patchy at best on warning about non-standard code.</p>
<ul>
<li><p>Mathematical functions such as <code class="calibre2">sqrt</code> are defined in C++ for floating-point arguments. It is legitimate in C++ to overload these with versions for types <code class="calibre2">float</code>, <code class="calibre2">double</code>, <code class="calibre2">long double</code> and possibly more. This means that calling <code class="calibre2">sqrt</code> on an integer type may have ‘overloading ambiguity’ as it could be promoted to any of the supported floating-point types: this is commonly seen on Solaris, but for <code class="calibre2">pow</code> also seen on macOS. (C++98 has an overload for <code class="calibre2">std::pow(&lt;double&gt;, &lt;int&gt;)</code>, but this may not be visible from the main namespace. C++11 requires additional overloads for integer types, and ambiguous overloads are more common in C++11 (and later) compiler modes.)</p>
<p>A not-uncommonly-seen problem is to mistakenly call <code class="calibre2">floor(x/y)</code> or <code class="calibre2">ceil(x/y)</code> for <code class="calibre2">int</code> arguments <code class="calibre2">x</code> and <code class="calibre2">y</code>. Since <code class="calibre2">x/y</code> does integer division, the result is an <code class="calibre2">int</code> and ‘overloading ambiguity’ may be reported. Some people have (pointlessly) called <code class="calibre2">floor</code> and <code class="calibre2">ceil</code> on integer arguments, which may have an ‘overloading ambiguity’.</p>
<p>A surprising common misuse is things like <code class="calibre2">pow(10, -3)</code>: this should be the constant <code class="calibre2">1e-3</code>.</p></li>
<li>Function <code class="calibre2">fabs</code> is defined only for floating-point types, except in C++11 which has overloads for <code class="calibre2">std::fabs</code> in &lt;cmath&gt; for integer types. Function <code class="calibre2">abs</code> is defined in C99’s &lt;stdlib.h&gt; for <code class="calibre2">int</code> and in C++98’s &lt;cstdlib&gt; for integer types, overloaded in &lt;cmath&gt; for floating-point types. C++11 has additional overloads for <code class="calibre2">std::abs</code> in &lt;cmath&gt; for integer types. The effect of calling <code class="calibre2">abs</code> with a floating-point type is implementation-specific: it may truncate to an integer.</li>
<li><p>Functions/macros such as <code class="calibre2">isnan</code>, <code class="calibre2">isinf</code> and <code class="calibre2">isfinite</code> are not required by C++98: where compilers support them they may be only in the <code class="calibre2">std</code> namespace or only in the main namespace. There is no way to make use of these functions which works with all C++ compilers currently in use on R platforms: use R’s versions such as <code class="calibre2">ISNAN</code> and <code class="calibre2">R_FINITE</code> instead.</p>
<p>If you must use them in C++11, beware that some compilers<a href="concept-index.html#FOOT88" id="DOCF88"><sup>88</sup></a> provide both <code class="calibre2">std::isnan</code> and <code class="calibre2">::isnan</code>, so using</p>
<div class="example">
<pre class="example1"><code>using namespace std;</code></pre>
</div>
<p>may cause ‘overloading ambiguity’ and you must use <code class="calibre2">std::isnan</code> <em>etc</em> explicitly.</p>
<p>It is an error (and make little sense, although has been seen) to call these functions for integer arguments: a few compilers give a compilation error.</p></li>
<li><p>The GNU C/C++ compilers support a large number of non-portable extensions. For example, <code class="calibre2">INFINITY</code> (which is in C99 but not C++98), for which R provides the portable <code class="calibre2">R_PosInf</code> (and <code class="calibre2">R_NegInf</code> for <code class="calibre2">-INFINITY</code>). And <code class="calibre2">NAN</code> is just one NaN value: in R code <code class="calibre2">NA_REAL</code> is usually what is intended, but <code class="calibre2">R_NaN</code> is also available.</p>
<p>Some (but not all) extensions are listed at <a href="https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html" class="uri">https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html</a> and <a href="https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Extensions.html" class="uri">https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Extensions.html</a>.</p>
<p>Other GNU extensions which have bitten package writers is the use of non-portable characters such as ‘&#36;’ in identifiers and use of C++ headers under ext.</p>
<p>The GNU Fortran compiler also supports a large number of non-portable extensions, the most commonly encountered one being <code class="calibre2">ISNAN</code><a href="concept-index.html#FOOT89" id="DOCF89"><sup>89</sup></a>. Some are listed at <a href="https://gcc.gnu.org/onlinedocs/gfortran/Extensions-implemented-in-GNU-Fortran.html" class="uri">https://gcc.gnu.org/onlinedocs/gfortran/Extensions-implemented-in-GNU-Fortran.html</a>. One that frequently catches package writers is that it allows out-of-order declarations: in standard-conformant Fortran variables must be declared (explicitly or implicitly) before use in other declarations such as dimensions.</p></li>
<li>Including C-style headers in C++ code is not portable. Including the legacy header<a href="concept-index.html#FOOT90" id="DOCF90"><sup>90</sup></a> math.h in C++ code may conflict with cmath which may be included by other headers. This is particularly problematic with C++11 compilers, as functions like <code class="calibre2">sqrt</code> and <code class="calibre2">isnan</code> are defined for <code class="calibre2">double</code> arguments in math.h and for a range of types including <code class="calibre2">double</code> in cmath. Similar issues have been seen for stdlib.h and cstdlib. Including the C++ version first used to be a sufficient workaround but for some 2016 compilers only one could be included.</li>
<li>Variable-length arrays are C99, not supported by C++98 nor by the C++ compilers in use with R on some platforms.</li>
<li>The <code class="calibre2">restrict</code> qualifier is C99/C11 but not part of C++11 and not supported by some C++ compilers used with R.</li>
<li><p>Be careful to include the headers which define the functions you use. Some compilers/OSes include other system headers in their headers which are not required by the standards, and so code may compile on such systems and not on others. (A prominent example is the C++11 header <code class="calibre2">&lt;random&gt;</code> which is indirectly included by <code class="calibre2">&lt;algorithm&gt;</code> by <code class="calibre2">g++</code>. Another issue is the C header <code class="calibre2">&lt;time.h&gt;</code> which is included by other headers on Linux and Windows but not macOS nor Solaris.)</p>
<p>Note that <code class="calibre2">malloc</code>, <code class="calibre2">calloc</code>, <code class="calibre2">realloc</code> and <code class="calibre2">free</code> are defined by C99 in the header stdlib.h and (in the <code class="calibre2">std::</code> namespace) by C++ header cstdlib. Some earlier implementations used a header malloc.h, but that is not portable and does not exist on macOS.</p>
<p>This also applies to types such as <code class="calibre2">ssize_t</code>. The POSIX standards say that is declared in headers <code class="calibre2">unistd.h</code> and <code class="calibre2">sys/types.h</code>, and the latter is often included indirectly by other headers on some but not all systems.</p>
<p>Similarly for constants: for example <code class="calibre2">SIZE_MAX</code> is defined in <code class="calibre2">stdint.h</code> alongside <code class="calibre2">size_t</code> (according to the C99 standard: it is not part of C++98).</p></li>
<li><p>For C++ code, be careful to specify namespaces where needed. Many functions are defined by the standards to be in the <code class="calibre2">std</code> namespace, but <code class="calibre2">g++</code> puts many such also in the C++ main namespace. One way to do so is to use declarations such as</p>
<div class="example">
<pre class="example1"><code>using std::floor;</code></pre>
</div>
<p>but it is usually preferable to use explicit namespace prefixes in the code.</p>
<p>Examples seen in CRAN packages include</p>
<div class="example">
<pre class="example1"><code>abs acos atan calloc ceil div exp fabs floor fmod free log malloc memcpy
memset pow printf qsort round sin sprintf sqrt strcmp strcpy strerror
strlen strncmp strtol tan trunc</code></pre>
</div></li>
<li><p>Some C++ compilers refuse to compile constructs such as</p>
<div class="example">
<pre class="example1"><code>      if(ptr &gt; 0) { ....}</code></pre>
</div>
<p>which compares a pointer to the integer <code class="calibre2">0</code>. This could just use <code class="calibre2">if(ptr)</code> (pointer addresses cannot be negative) but if needed pointers can be tested against <code class="calibre2">nullptr</code> (C++11 and later) or <code class="calibre2">NULL</code>.</p>
<p>Note that although <code class="calibre2">nullptr</code> was only introduced in C++11, some compilers accept it in C++98 mode (but most do not).</p></li>
<li>Macros defined by the compiler/OS can cause problems. Identifiers starting with an underscore followed by an upper-case letter or another underscore are reserved for system macros and should not be used in portable code (including not as guards in C/C++ headers). Other macros, typically upper-case, may be defined by the compiler or system headers and can cause problems. The most common issue involves the names of the Intel CPU registers such as <code class="calibre2">CS</code>, <code class="calibre2">DS</code>, <code class="calibre2">ES</code>, <code class="calibre2">FS</code>, <code class="calibre2">GS</code> and <code class="calibre2">SS</code> (and more with longer abbreviations) defined on i586/x64 Solaris in &lt;sys/regset.h&gt; and often included indirectly by &lt;stdlib.h&gt; and other core headers. Further examples are <code class="calibre2">ERR</code>, <code class="calibre2">LITTLE_ENDIAN</code>, <code class="calibre2">zero</code> and <code class="calibre2">I</code> (which is defined in Solaris’ &lt;complex.h&gt; as a compiler intrinsic for the imaginary unit). Some of these can be avoided by defining <code class="calibre2">_POSIX_C_SOURCE</code> before including any system headers, but it is better to only use all-upper-case names which have a unique prefix such as the package name.</li>
<li><code class="calibre2">typedef</code>s in OS headers can conflict with those in the package: examples include <code class="calibre2">ulong</code> on several OSes and <code class="calibre2">index_t</code> and <code class="calibre2">single</code> on Solaris. (Note that these may conflict with other uses as identifiers, e.g. defining a C++ function called <code class="calibre2">single</code>.)</li>
<li><p>If you use OpenMP, check carefully that you have followed the advice in the subsection on <a href="creating-r-packages.html#OpenMP-support">OpenMP support</a>. In particular, any use of OpenMP in C/C++ code will need to use</p>
<div class="example">
<pre class="example1"><code>#ifdef _OPENMP
# include &lt;omp.h&gt;
#endif</code></pre>
</div>
<p>Any use of OpenMP functions, e.g. <code class="calibre2">omp_set_num_threads</code> also needs to be conditioned.</p>
<p>And do not hardcode -lgomp: not only is that specific to the GCC family of compilers, using the correct linker flag often sets up the run-time path to the library.</p></li>
<li><p>Package authors commonly assume things are part of C99 when they are not: the most common example is POSIX function <code class="calibre2">strdup</code>. The most common C library on Linux, <code class="calibre2">glibc</code>, will hide the declarations of such extensions unless a ‘feature-test macro’ is defined <strong>before</strong> (almost) any system header is included. So for <code class="calibre2">strdup</code> you need</p>
<div class="example">
<pre class="example1"><code>#define _POSIX_C_SOURCE 200809L
...
#include &lt;string.h&gt;
...
strdup call(s)</code></pre>
</div>
<p>where the appropriate value can be found by <code class="calibre2">man strdup</code> on Linux. (Use of <code class="calibre2">strncasecmp</code> is similar.)</p>
<p>However, modes of <code class="calibre2">gcc</code> with ‘GNU EXTENSIONS’ (which are the default, either -std=gnu99 or -std=gnu11) declare enough macros to ensure that missing declarations are rarely seen.</p>
<p>This applies also to constants such as <code class="calibre2">M_PI</code> and <code class="calibre2">M_LN2</code>, which are part of the X/Open standard: to use these define <code class="calibre2">_XOPEN_SOURCE</code> before including any headers, or include the R header Rmath.h.</p></li>
<li><p>Similarly, package authors commonly assume things are part of C++ when they were introduced in C++11 if at all. Recent examples from CRAN packages include the C99/C++11 functions</p>
<div class="example">
<pre class="example1"><code>erf expm1 fmin fmax lgamma lround loglp round snprintf strcasecmp trunc</code></pre>
</div>
<p>(all of which are in the <code class="calibre2">std</code> namespace in C++11) and the POSIX functions <code class="calibre2">strdup</code> and <code class="calibre2">strncasecmp</code> and constants <code class="calibre2">M_PI</code> and <code class="calibre2">M_LN2</code> (see the previous item). R has long provided <code class="calibre2">fmax2</code>, <code class="calibre2">fmin2</code>, <code class="calibre2">fround</code>, <code class="calibre2">ftrunc</code>, <code class="calibre2">lgammafn</code> and many of the X/Open constants, declared in header Rmath.h. Uses of <code class="calibre2">erf</code> can be replaced by <code class="calibre2">pnorm</code> (see the R help page for the latter).</p></li>
<li>Using <code class="calibre2">alloca</code> portably is tricky: it is neither an ISO C nor a POSIX function. An adequately portable preamble is
<div class="example">
<pre class="example1"><code>#ifdef __GNUC__
/* Includes GCC, clang and Intel compilers */
# undef alloca
# define alloca(x) __builtin_alloca((x))
#elif defined(__sun) || defined(_AIX)
/* this is necessary (and sufficient) for Solaris 10 and AIX 6: */
# include &lt;alloca.h&gt;
#endif</code></pre>
</div></li>
</ul>
<p>Some additional information for C++ is available at <a href="http://journal.r-project.org/archive/2011-2/RJournal_2011-2_Plummer.pdf" class="uri">http://journal.r-project.org/archive/2011-2/RJournal_2011-2_Plummer.pdf</a> by Martyn Plummer.</p>
<hr />
<p><a href="" id="Binary-distribution"></a> <a href="" id="Binary-distribution-1"></a></p>
<h4 id="binary-distribution" class="subsection">1.6.5 Binary distribution</h4>
<p>If you want to distribute a binary version of a package on Windows or OS X, there are further checks you need to do to check it is portable: it is all too easy to depend on external software on your own machine that other users will not have.</p>
<p>For Windows, check what other DLLs your package’s DLL depends on (‘imports’ from in the DLL tools’ parlance). A convenient GUI-based tool to do so is ‘Dependency Walker’ (<a href="http://www.dependencywalker.com/" class="uri">http://www.dependencywalker.com/</a>) for both 32-bit and 64-bit DLLs – note that this will report as missing links to R’s own DLLs such as R.dll and Rblas.dll. For 32-bit DLLs only, the command-line tool <code class="calibre2">pedump.exe -i</code> (in Rtools*.exe) can be used, and for the brave, the <code class="calibre2">objdump</code> tool in the appropriate toolchain will also reveal what DLLs are imported from. If you use a toolchain other than one provided by the R developers or use your own makefiles, watch out in particular for dependencies on the toolchain’s runtime DLLs such as libgfortran, libstdc++ and libgcc_s.</p>
<p>For macOS, using <code class="calibre2">R CMD otool -L</code> on the package’s shared object(s) in the libs directory will show what they depend on: watch for any dependencies in /usr/local/lib or /usr/local/gfortran/lib, notably libgfortran.?.dylib and libquadmath.0.dylib.</p>
<p>Many people (including the CRAN package repository) will not accept source packages containing binary files as the latter are a security risk. If you want to distribute a source package which needs external software on Windows or macOS, options include</p>
<ul>
<li>To arrange for installation of the package to download the additional software from a URL, as e.g. package <a href="https://CRAN.R-project.org/package=Cairo"><strong>Cairo</strong></a> does.</li>
<li>(For CRAN.) To negotiate with Uwe Ligges to host the additional components on WinBuilder, and write a configure.win file to install them.</li>
</ul>
<p>Be aware that license requirements will need to be met so you may need to supply the sources for the additional components (and will if your package has a GPL-like license).</p>
<hr />
<p><a href="" id="Diagnostic-messages"></a> <a href="" id="Diagnostic-messages-1"></a></p>
<h3 id="diagnostic-messages" class="section">1.7 Diagnostic messages</h3>
<p>Diagnostic messages can be made available for translation, so it is important to write them in a consistent style. Using the tools described in the next section to extract all the messages can give a useful overview of your consistency (or lack of it). Some guidelines follow.</p>
<ul>
<li>Messages are sentence fragments, and not viewed in isolation. So it is conventional not to capitalize the first word and not to end with a period (or other punctuation).</li>
<li><p>Try not to split up messages into small pieces. In C error messages use a single format string containing all English words in the messages.</p>
<p>In R error messages do not construct a message with <code class="calibre2">paste</code> (such messages will not be translated) but <em>via</em> multiple arguments to <code class="calibre2">stop</code> or <code class="calibre2">warning</code>, or <em>via</em> <code class="calibre2">gettextf</code>.</p></li>
<li>Do not use colloquialisms such as “can’t” and “don’t”.</li>
<li><p>Conventionally single quotation marks are used for quotations such as</p>
<div class="example">
<pre class="example1"><code>&#39;ord&#39; must be a positive integer, at most the number of knots</code></pre>
</div>
<p>and double quotation marks when referring to an R character string or a class, such as</p>
<div class="example">
<pre class="example1"><code>&#39;format&#39; must be &quot;normal&quot; or &quot;short&quot; - using &quot;normal&quot;</code></pre>
</div>
<p>Since ASCII does not contain directional quotation marks, it is best to use ‘'’ and let the translator (including automatic translation) use directional quotations where available. The range of quotation styles is immense: unfortunately we cannot reproduce them in a portable <code class="calibre2">texinfo</code> document. But as a taster, some languages use ‘up’ and ‘down’ (comma) quotes rather than left or right quotes, and some use guillemets (and some use what Adobe calls ‘guillemotleft’ to start and others use it to end).</p>
<p>In R messages it is also possible to use <code class="calibre2">sQuote</code> or <code class="calibre2">dQuote</code> as in</p>
<div class="example">
<pre class="example1"><code>        stop(gettextf(&quot;object must be of class %s or %s&quot;,
                      dQuote(&quot;manova&quot;), dQuote(&quot;maov&quot;)),
             domain = NA)</code></pre>
</div></li>
<li><p>Occasionally messages need to be singular or plural (and in other languages there may be no such concept or several plural forms – Slovenian has four). So avoid constructions such as was once used in <code class="calibre2">library</code></p>
<div class="example">
<pre class="example1"><code>if((length(nopkgs) &gt; 0) &amp;&amp; !missing(lib.loc)) {
    if(length(nopkgs) &gt; 1)
        warning(&quot;libraries &quot;,
                paste(sQuote(nopkgs), collapse = &quot;, &quot;),
                &quot; contain no packages&quot;)
    else
        warning(&quot;library &quot;, paste(sQuote(nopkgs)),
                &quot; contains no package&quot;)
}</code></pre>
</div>
<p>and was replaced by</p>
<div class="example">
<pre class="example1"><code>if((length(nopkgs) &gt; 0) &amp;&amp; !missing(lib.loc)) {
    pkglist &lt;- paste(sQuote(nopkgs), collapse = &quot;, &quot;)
    msg &lt;- sprintf(ngettext(length(nopkgs),
                            &quot;library %s contains no packages&quot;,
                            &quot;libraries %s contain no packages&quot;,
                            domain = &quot;R-base&quot;),
                   pkglist)
    warning(msg, domain=NA)
}</code></pre>
</div>
<p>Note that it is much better to have complete clauses as here, since in another language one might need to say ‘There is no package in library %s’ or ‘There are no packages in libraries %s’.</p></li>
</ul>
<hr />
<p><a href="" id="Internationalization"></a> <a href="" id="Internationalization-1"></a></p>
<h3 id="internationalization" class="section">1.8 Internationalization</h3>
<p>There are mechanisms to translate the R- and C-level error and warning messages. There are only available if R is compiled with NLS support (which is requested by <code class="calibre2">configure</code> option --enable-nls, the default).</p>
<p>The procedures make use of <code class="calibre2">msgfmt</code> and <code class="calibre2">xgettext</code> which are part of GNU <code class="calibre2">gettext</code> and this will need to be installed: Windows users can find pre-compiled binaries at <a href="https://www.stats.ox.ac.uk/pub/Rtools/goodies/gettext-tools.zip" class="uri">https://www.stats.ox.ac.uk/pub/Rtools/goodies/gettext-tools.zip</a>.</p>
<hr />
<p><a href="" id="C_002dlevel-messages"></a> <a href="" id="C_002dlevel-messages-1"></a></p>
<h4 id="c-level-messages" class="subsection">1.8.1 C-level messages</h4>
<p>The process of enabling translations is</p>
<ul>
<li>In a header file that will be included in all the C (or C++ or Objective C/C++) files containing messages that should be translated, declare
<div class="example">
<pre class="example1"><code>#include &lt;R.h&gt;  /* to include Rconfig.h */

#ifdef ENABLE_NLS
#include &lt;libintl.h&gt;
#define _(String) dgettext (&quot;pkg&quot;, String)
/* replace pkg as appropriate */
#else
#define _(String) (String)
#endif</code></pre>
</div></li>
<li><p>For each message that should be translated, wrap it in <code class="calibre2">_(...)</code>, for example</p>
<div class="example">
<pre class="example1"><code>error(_(&quot;&#39;ord&#39; must be a positive integer&quot;));</code></pre>
</div>
<p>If you want to use different messages for singular and plural forms, you need to add</p>
<div class="example">
<pre class="example1"><code>#ifndef ENABLE_NLS
#define dngettext(pkg, String, StringP, N) (N &gt; 1 ? StringP : String)
#endif</code></pre>
</div>
<p>and mark strings by</p>
<div class="example">
<pre class="example1"><code>dngettext(&quot;pkg&quot;, &lt;singular string&gt;, &lt;plural string&gt;, n)</code></pre>
</div></li>
<li>In the package’s src directory run
<div class="example">
<pre class="example1"><code>xgettext --keyword=_ -o pkg.pot *.c</code></pre>
</div></li>
</ul>
<p>The file src/pkg.pot is the template file, and conventionally this is shipped as po/pkg.pot.</p>
<hr />
<p><a href="" id="R-messages"></a> <a href="" id="R-messages-1"></a></p>
<h4 id="r-messages" class="subsection">1.8.2 R messages</h4>
<p>Mechanisms are also available to support the automatic translation of R <code class="calibre2">stop</code>, <code class="calibre2">warning</code> and <code class="calibre2">message</code> messages. They make use of message catalogs in the same way as C-level messages, but using domain <code class="calibre2">R-pkg</code> rather than <code class="calibre2">pkg</code>. Translation of character strings inside <code class="calibre2">stop</code>, <code class="calibre2">warning</code> and <code class="calibre2">message</code> calls is automatically enabled, as well as other messages enclosed in calls to <code class="calibre2">gettext</code> or <code class="calibre2">gettextf</code>. (To suppress this, use argument <code class="calibre2">domain=NA</code>.)</p>
<p>Tools to prepare the R-pkg.pot file are provided in package <strong>tools</strong>: <code class="calibre2">xgettext2pot</code> will prepare a file from all strings occurring inside <code class="calibre2">gettext</code>/<code class="calibre2">gettextf</code>, <code class="calibre2">stop</code>, <code class="calibre2">warning</code> and <code class="calibre2">message</code> calls. Some of these are likely to be spurious and so the file is likely to need manual editing. <code class="calibre2">xgettext</code> extracts the actual calls and so is more useful when tidying up error messages.</p>
<p>The R function <code class="calibre2">ngettext</code> provides an interface to the C function of the same name: see example in the previous section. It is safest to use <code class="calibre2">domain=&quot;R-pkg&quot;</code> explicitly in calls to <code class="calibre2">ngettext</code>, and necessary for earlier versions of R unless they are calls directly from a function in the package.</p>
<hr />
<p><a href="" id="Preparing-translations"></a> <a href="" id="Preparing-translations-1"></a></p>
<h4 id="preparing-translations" class="subsection">1.8.3 Preparing translations</h4>
<p>Once the template files have been created, translations can be made. Conventional translations have file extension .po and are placed in the po subdirectory of the package with a name that is either ‘ll.po’ or ‘R-ll.po’ for translations of the C and R messages respectively to language with code ‘ll’.</p>
<p>See ‘Localization of messages’ in ‘R Installation and Administration’, for details of language codes.</p>
<p>There is an R function, <code class="calibre2">update_pkg_po</code> in package <strong>tools</strong>, to automate much of the maintenance of message translations. See its help for what it does in detail.</p>
<p>If this is called on a package with no existing translations, it creates the directory pkgdir/po, creates a template file of R messages, pkgdir/po/R-pkg.pot, within it, creates the ‘en@quot’ translation and installs that. (The ‘en@quot’ pseudo-language interprets quotes in their directional forms in suitable (e.g. UTF-8) locales.)</p>
<p>If the package has C source files in its src directory that are marked for translation, use</p>
<div class="example">
<pre class="example1"><code>touch pkgdir/po/pkg.pot</code></pre>
</div>
<p>to create a dummy template file, then call <code class="calibre2">update_pkg_po</code> again (this can also be done before it is called for the first time).</p>
<p>When translations to new languages are added in the pkgdir/po directory, running the same command will check and then install the translations.</p>
<p>If the package sources are updated, the same command will update the template files, merge the changes into the translation .po files and then installed the updated translations. You will often see that merging marks translations as ‘fuzzy’ and this is reported in the coverage statistics. As fuzzy translations are <em>not</em> used, this is an indication that the translation files need human attention.</p>
<p>The merged translations are run through <code class="calibre2">tools::checkPofile</code> to check that C-style formats are used correctly: if not the mismatches are reported and the broken translations are not installed.</p>
<p>This function needs the GNU <code class="calibre2">gettext-tools</code> installed and on the path: see its help page.</p>
<p><a href="" id="index-CITATION-1"></a> <a href="" id="index-citation-1"></a></p>
<hr />
<p><a href="" id="CITATION-files"></a> <a href="" id="CITATION-files-1"></a></p>
<h3 id="citation-files" class="section">1.9 CITATION files</h3>
<p>An installed file named CITATION will be used by the <code class="calibre2">citation()</code> function. (It should be in the inst subdirectory of the package sources.)</p>
<p>The CITATION file is parsed as R code (in the package’s declared encoding, or in ASCII if none is declared). If no such file is present, <code class="calibre2">citation</code> auto-generates citation information from the package DESCRIPTION metadata, and an example of what that would look like as a CITATION file can be seen in recommended package <a href="https://CRAN.R-project.org/package=nlme"><strong>nlme</strong></a> (see below): recommended packages <a href="https://CRAN.R-project.org/package=boot"><strong>boot</strong></a>, <a href="https://CRAN.R-project.org/package=cluster"><strong>cluster</strong></a> and <a href="https://CRAN.R-project.org/package=mgcv"><strong>mgcv</strong></a> have further examples.</p>
<p>A CITATION file will contain calls to function <code class="calibre2">bibentry</code>.</p>
<p>Here is that for <a href="https://CRAN.R-project.org/package=nlme"><strong>nlme</strong></a>:</p>
<div class="example">
<pre class="example1"><code>year &lt;- sub(&quot;-.*&quot;, &quot;&quot;, meta&#36;Date)
note &lt;- sprintf(&quot;R package version %s&quot;, meta&#36;Version)

bibentry(bibtype = &quot;Manual&quot;,
         title = &quot;{nlme}: Linear and Nonlinear Mixed Effects Models&quot;,
         author = c(person(&quot;Jose&quot;, &quot;Pinheiro&quot;),
                    person(&quot;Douglas&quot;, &quot;Bates&quot;),
                    person(&quot;Saikat&quot;, &quot;DebRoy&quot;),
                    person(&quot;Deepayan&quot;, &quot;Sarkar&quot;),
                    person(&quot;R Core Team&quot;)),
         year = year,
         note = note,
         url = &quot;https://CRAN.R-project.org/package=nlme&quot;)</code></pre>
</div>
<p>Note the way that information that may need to be updated is picked up from object <code class="calibre2">meta</code>, a parsed version of the DESCRIPTION file – it is tempting to hardcode such information, but it normally then gets outdated. See <code class="calibre2">?bibentry</code> for further details of the information which can be provided.</p>
<p>In case a bibentry contains LaTeX markup (e.g., for accented characters or mathematical symbols), it may be necessary to provide a text representation to be used for printing via the <code class="calibre2">textVersion</code> argument to <code class="calibre2">bibentry</code>. E.g., earlier versions of <a href="https://CRAN.R-project.org/package=nlme"><strong>nlme</strong></a> additionally used</p>
<div class="example">
<pre class="example1"><code>         textVersion =
         paste0(&quot;Jose Pinheiro, Douglas Bates, Saikat DebRoy,&quot;,
                &quot;Deepayan Sarkar and the R Core Team (&quot;,
                year,
                &quot;). nlme: Linear and Nonlinear Mixed Effects Models. &quot;,
                note, &quot;.&quot;)</code></pre>
</div>
<p>The CITATION file should itself produce no output when <code class="calibre2">source</code>-d.</p>
<p>It is desirable (and essential for CRAN) that the CITATION file does not contain calls to functions such as <code class="calibre2">packageDescription</code> which assume the package is installed in a library tree on the package search path.</p>
<hr />
<p><a href="" id="Package-types"></a> <a href="" id="Package-types-1"></a></p>
<h3 id="package-types" class="section">1.10 Package types</h3>
<p>The DESCRIPTION file has an optional field <code class="calibre2">Type</code> which if missing is assumed to be ‘Package’, the sort of extension discussed so far in this chapter. Currently one other type is recognized; there used also to be a ‘Translation’ type.</p>
<hr />
<p><a href="" id="Frontend"></a> <a href="" id="Frontend-1"></a></p>
<h4 id="frontend" class="subsection">1.10.1 Frontend</h4>
<p>This is a rather general mechanism, designed for adding new front-ends such as the former <strong>gnomeGUI</strong> package (see the Archive area on CRAN). If a configure file is found in the top-level directory of the package it is executed, and then if a Makefile is found (often generated by configure), <code class="calibre2">make</code> is called. If <code class="calibre2">R CMD INSTALL --clean</code> is used <code class="calibre2">make clean</code> is called. No other action is taken.</p>
<p><code class="calibre2">R CMD build</code> can package up this type of extension, but <code class="calibre2">R CMD check</code> will check the type and skip it.</p>
<p>Many packages of this type need write permission for the R installation directory.</p>
<hr />
<p><a href="" id="Services"></a> <a href="" id="Services-1"></a></p>
<h3 id="services" class="section">1.11 Services</h3>
<p>Several members of the R project have set up services to assist those writing R packages, particularly those intended for public distribution.</p>
<p><a href="https://win-builder.r-project.org">win-builder.r-project.org</a> offers the automated preparation of (32/64-bit) Windows binaries from well-tested source packages.</p>
<p>R-Forge (<a href="https://R-Forge.r-project.org">R-Forge.r-project.org</a>) and RForge (<a href="https://www.rforge.net">www.rforge.net</a>) are similar services with similar names. Both provide source-code management through SVN, daily building and checking, mailing lists and a repository that can be accessed <em>via</em> <code class="calibre2">install.packages</code> (they can be selected by <code class="calibre2">setRepositories</code> and the GUI menus that use it). Package developers have the opportunity to present their work on the basis of project websites or news announcements. Mailing lists, forums or wikis provide useRs with convenient instruments for discussions and for exchanging information between developers and/or interested useRs.</p>
<hr />
<p><a href="" id="Writing-R-documentation-files"></a> <a href="" id="Writing-R-documentation-files-1"></a></p>
<div id="calibre_pb_6" class="calibre6">

</div>








